### ISSUE TITLE
Crackles/pops on mobiles

### ISSUE THREAD

**Issue by MentalBlood** [generative-music/generative.fm#210]
Hi, I was really delighted when found your app. It works fine on my PC (Chrome), but there crackles every few seconds when listening to it on mobile. I tested on iphone XR (Safari, also tried Chrome but it looks like that on iOS they have same engine) and Xiaomi Mi Max 3 (Chrome). Is it because of CPU overload, or there some other reasons? I have some experience in programming (including frontend), so you don't have to waste time simplifying the answer.

P.S. Anyway, thank you for such app

**Comment by metalex9** [comment]
Hi @MentalBlood, thanks for sharing your experience. You're exactly right, the crackling and popping is due to high CPU usage. See https://github.com/generative-music/generative.fm/issues/206#issuecomment-639197135 for more details.

I'm actually going through the pieces one by one right now to reduce the CPU usage in as many as I can, but it will take some weeks to complete. I'll update here once that's done.

**Comment by metalex9** [comment]
Hi again @MentalBlood. I wanted to let you know I just released v1.36.0 which should significantly reduce any audio issues like this.

**Comment by metalex9** [comment]
I've received positive feedback that this issue was significantly improved with my changes, so I'm closing this. We can reopen if we need to.
