### ISSUE TITLE
Add ability to generate recordings

### ISSUE THREAD

**Issue by qazip** [generative-music/generative.fm#28]
Original issue: It would be awesome if we could play it for a certain period of time and then be able to save what was played.

EDIT: Probably offer some form where users can input the length of recording they'd like (with some reasonable maximum). Then a music file of that length is generated and downloaded.

**Comment by metalex9** [comment]
@qazip I just realized that you described a "live recording" feature (where you can listen along as it records). However, what I actually implemented in #88 was to generate recordings without the ability to listen, as they typically generate faster than real time. I'm going to continue treating this issue as "recording generation," and I'll make a separate issue for "live recording" and link it here, just in case the ability to listen along was important. Otherwise, hopefully what I implemented in #88 will suffice.

**Comment by metalex9** [comment]
Issue for live recording here: #89

**Comment by qazip** [comment]
I don't need live-recording. The current implemention of generating recordings is good enough for me. The files are incredibly big though. I was not expecting a 30min to have a size of 300mb.

**Comment by metalex9** [comment]
@qazip I can't imagine you still care, but just in case, I wanted to let you know [the new recording app](https://record.generative.fm) produces significantly smaller files.
